### ISSUE TITLE
Choose Mpd audio output

### ISSUE THREAD

**Issue by johnsen** [jmechnich/qmpc#2]
Hi,

I've setup 2 audio outputs on my RPI with Volumio, but it doesn't seems to be possible to choose one of the outputs to use in qmpc on my N900.

**Comment by jmechnich** [comment]
Hi johnsen,

I wasn't even aware that this feature existed. :)
Anyways, I have added another item to the menu for toggling mpd outputs. Let me know if it works for you...

Cheers,
Joerg

**Comment by grammoboy2** [comment]
Man, works perfect. Thanks a lot! Really appreciated. Ha, the N900 is still
alive. I've bought my third one on ebay yesterday, after the others broke
:)

**Comment by jmechnich** [comment]
I am actually surprised that mine is still working after five years, even with the first battery.
Good luck with your third one.

**Comment by grammoboy2** [comment]
Btw what is 'single' and 'consume'?

**Comment by jmechnich** [comment]
Those are specific playback modes of MPD:
"Single mode makes MPD not progres to the next song. "
"Consume mode makes MPD remove played songs from the play-queue."
(from http://gmpclient.org/Manual/Manual.html)
For example, if you wanted to repeat one song, you could enable both 'Repeat' and 'Single' (as 'Repeat' corresponds to 'Repeat All').

**Comment by grammoboy2** [comment]
Ok thx. Output set to pulse output doesn't work always flawless
(stuttering), but that could be a N900 pulseaudio issue.
